import { createTheme } from "@mui/material";

// const theme = createTheme({
//   status: {
//     danger: orange[500],
//   },
// });

const defaultTheme = createTheme({
  colors: {
    primary: "#4455F4",
    secondary: "#3dc2ff",
    tertiary: "#5260ff",
    success: "#2dd36f",
    warning: "#ffc409",
    danger: "#eb445a",
    dark: "#222428",
    medium: "#92949c",
    light: "#f4f5f8",
    lightmedium: "#f2f2f6",
    "pokemon-ghost": "#65539d",
    "pokemon-steel": "#908da9",
    "pokemon-dragon": "#3b3bbb",
    "pokemon-flying": "#7a9ff2",
    "pokemon-water": "#3a8be9",
    "pokemon-ice": "#3a8be9",
    "pokemon-unknown": "#255147",
    "pokemon-grass": "#4fb443",
    "pokemon-bug": "#889e2a",
    "pokemon-normal": "#afa485",
    "pokemon-electric": "#f4c234",
    "pokemon-ground": "#b7904b",
    "pokemon-rock": "#b7904b",
    "pokemon-fire": "#e76b2f",
    "pokemon-fighting": "#9b4840",
    "pokemon-dark": "#5e4c4c",
    "pokemon-psychic": "#f5779e",
    "pokemon-fairy": "#f9a8ef",
    "pokemon-poison": "#a15ab1",
    "bg-pokemon-ghost": "#cbc1e8",
    "bg-pokemon-steel": "#d9d7e5",
    "bg-pokemon-dragon": "#b9b9fc",
    "bg-pokemon-flying": "#cbdeff",
    "bg-pokemon-water": "#afd9ff",
    "bg-pokemon-ice": "#afd9ff",
    "bg-pokemon-unknown": "#255147",
    "bg-pokemon-grass": "#b5eaaf",
    "bg-pokemon-bug": "#d4dfa7",
    "bg-pokemon-normal": "#e4e0cf",
    "bg-pokemon-electric": "#ffe9a7",
    "bg-pokemon-ground": "#ecd8b4",
    "bg-pokemon-rock": "#ecd8b4",
    "bg-pokemon-fire": "#ffc8a9",
    "bg-pokemon-fighting": "#e7bdb8",
    "bg-pokemon-dark": "#c9c0c0",
    "bg-pokemon-psychic": "#ffcbde",
    "bg-pokemon-fairy": "#fdf",
    "bg-pokemon-poison": "#e6c2ef",
  },
});

export default defaultTheme;
