import { IPets } from "../../context/types";

export const initialTab = [
  { category: "moves", name: "Moves" },
  { category: "stats", name: "Stats" },
  // { category: "about", name: "About" },
];

export interface IImagePokemon {
  name: string;
  id: string | number;
}
export interface IConfirm {
  visible: boolean;
  id: string | number;
  nickname: string;
}

export interface IColorPokemon {
  primary: string;
  secondary: string;
  tertiary: string;
  success: string;
  warning: string;
  danger: string;
  dark: string;
  medium: string;
  light: string;
  lightmedium: string;
  "pokemon-ghost": string;
  "pokemon-steel": string;
  "pokemon-dragon": string;
  "pokemon-flying": string;
  "pokemon-water": string;
  "pokemon-ice": string;
  "pokemon-unknown": string;
  "pokemon-grass": string;
  "pokemon-bug": string;
  "pokemon-normal": string;
  "pokemon-electric": string;
  "pokemon-ground": string;
  "pokemon-rock": string;
  "pokemon-fire": string;
  "pokemon-fighting": string;
  "pokemon-dark": string;
  "pokemon-psychic": string;
  "pokemon-fairy": string;
  "pokemon-poison": string;
  "bg-pokemon-ghost": string;
  "bg-pokemon-steel": string;
  "bg-pokemon-dragon": string;
  "bg-pokemon-flying": string;
  "bg-pokemon-water": string;
  "bg-pokemon-ice": string;
  "bg-pokemon-unknown": string;
  "bg-pokemon-grass": string;
  "bg-pokemon-bug": string;
  "bg-pokemon-normal": string;
  "bg-pokemon-electric": string;
  "bg-pokemon-ground": string;
  "bg-pokemon-rock": string;
  "bg-pokemon-fire": string;
  "bg-pokemon-fighting": string;
  "bg-pokemon-dark": string;
  "bg-pokemon-psychic": string;
  "bg-pokemon-fairy": string;
  "bg-pokemon-poison": string;
}

// Generated by https://quicktype.io

export interface IPokemonDetails {
  pokemon: Pokemon;
}

export interface Pokemon {
  id: number;
  name: string;
  sprites: Sprites;
  moves: MoveElement[];
  stats: {
    stat: {
      name: string;
    };
    base_stat: number;
  }[];
  types: Type[];
  __typename: string;
}

export interface MoveElement {
  move: TypeClass;
  __typename: PurpleTypename;
}

export enum PurpleTypename {
  Move = "Move",
}

export interface TypeClass {
  name: string;
  __typename: TypeTypename;
}

export enum TypeTypename {
  BaseName = "BaseName",
}

export interface Sprites {
  front_default: string;
  __typename: string;
}

export interface Type {
  type: TypeClass;
  __typename: string;
}

export interface IModals {
  visible: boolean;
  catching: boolean;
  success?: boolean;
  onDismiss: () => void;
  onSubmit: (event: React.FormEvent<HTMLFormElement>, nickname: string) => void;
  type?: string;
}

export interface IModalChoice {
  visible: boolean;
  onDismiss: () => void;
  onRemove: (id: string | number, nickname: string) => void;
  type?: string;
  listPokemon: IPets[];
  success?: boolean;
}

export interface IModalConfirm {
  visible: boolean;
  onDismiss: () => void;
  onAgree: () => void;
  title: string;
  subtitle?: string;
}
